---
abstract: 'L<Alien> wrapping for F<libtermkey>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  File::Basename: 0
  File::Path: 2.07
  File::Spec: 0
configure_requires:
  File::Basename: 0
  File::Path: 2.07
  File::Spec: 0
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-libtermkey
provides:
  Alien::libtermkey:
    file: lib/Alien/libtermkey.pm
    version: 0.15
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
